export const words = [
  // "banana",
  // "toaster",
  // "potato",
  // "socks",
  // "shampoo",
  "marshmallow",
  // "flipflop",
  // "imagine",
  // "inferno",
  // "eclipse",
  // "wizard",
  // "codex",
  // "cast",
  // "soul",
  // "shadow",
  // "flame",
  // "crystal",
  // "thunder",
  // "tornado",
  // "serpent",
  // "raven",
  // "vampire",
  // "wraith",
  // "demon",
  // "arcane",
  // "phantom",
  "control",
  // "escape",
  // "magic",
  "alive",
  "network",
  // "digital",
  // "kernel",
  "protocol",
  // "override",
  // "latency",
  // "burn",
  "checklist",
  // "therapy",
  "smile",
  // "smile",
  // "grow",
  // "firewall",
  // "glitch",
  // "hexcode",
  // "neon",
  // "ghost",
  // "quantum",
  "void",
  "task",
  "compliance",
  // "pulse",
  // "neurocircuit",
  // "spellcaster",
  // "configuration",
  // "neuralink",
  "neurofeed",
  "unicorn",
  // "deepfake",
  // "datamining",
  "backlog",
  "sprint",
  // "metaverse",
  // "biometric",
  "productivity",
  "mindless",
  "deadline",
  // "corporate",
  // "biochip",
  "doomscroll",
  "autosave",
  "vibeloop",
  "burnout",
  // "bigdata",
  "dashboard",
  "copilot",
  "monetize",
  "procrastinate",
  "dopamine",
  "multitask",
  // "human",
  "retention",
  "roadmap",
  // "restart",
  "followup",
  // "neurodata",
  "shadowban",
  // "stakeholder",
  "model",
  "monday",
  // "notification",
  "updates",
  // "scrolling",
  // "laser",
  "perform",
  "onboarding",
  "rejected",
  "escalate",
  "permission",
  "alignment",
  "rollback",
  "surveillance",
  // "mandatory",
  // "benchmark",
  "hallucinate",
  "deliver",
  "scalable",
  "urgent",
  "purpose",
  "growth",
  "prediction",
  "leadership",
  // "hotfix",
  // "replace",
  // "optimizer",
  "obsolete",
  "micromanagement",
  "dehumanization",
  "entrepreneurship",
  "corrupted",
  "efficiency",
  // "hydrate",
  "selfcare",
  "pipeline",
  "culture",
  "agent",
  "metrics",
  "teraflop",
  "layoff",
  "deploy",
  "autocode",
  "overload",
  // "null",
  "checklist",
  "privilege",
  // "pragmatic",
  // "stoic",
  // "panda",
  "workflow",
  // "exodus",
  // "stargate",
  // "wetware",
  "motivation",
  "corrupted",
  // "babilonia",
]


//

// 29/08 teste
// export const words = [
//  "smile",
//  "smile",

// ]
